// Split out from SettingsContext so it can be imported without dragging in the
// platform storage layer, which a plain unit test cannot load.
import {DEFAULT_HOME_ROWS} from '../utils/homeLayout';

export const defaultSettings = {
	preferTranscode: false,
	forceDirectPlay: false,
	experimentalTruehd: false,
	maxBitrate: 0,
	audioLanguage: '',
	subtitleLanguage: '',
	uiLanguage: 'en-US',
	subtitleMode: 'default',
	subtitleSize: 'medium',
	subtitlePosition: 'bottom',
	subtitleOpacity: 100,
	subtitleBackground: 0,
	subtitleBackgroundColor: '#000000',
	subtitleColor: '#ffffff',
	subtitleShadowColor: '#000000',
	subtitleShadowOpacity: 100,
	subtitleShadowBlur: 0.1,
	subtitlePositionAbsolute: 90,
	// White is far brighter in HDR than in SDR, so the HDR text color starts grey.
	subtitleHdrSeparate: false,
	subtitleSizeHdr: 'medium',
	subtitlePositionHdr: 'bottom',
	subtitleOpacityHdr: 100,
	subtitleBackgroundHdr: 0,
	subtitleBackgroundColorHdr: '#000000',
	subtitleColorHdr: '#808080',
	subtitleShadowColorHdr: '#000000',
	subtitleShadowOpacityHdr: 100,
	subtitleShadowBlurHdr: 0.1,
	subtitlePositionAbsoluteHdr: 90,
	seekStep: 10,
	fallbackAudioLanguage: '',
	preferDefaultAudioTrack: false,
	preferAudioDescription: false,
	fallbackSubtitleLanguage: '',
	preferSdhSubtitles: false,
	// Seconds as a string, the shape the other clients sync for it.
	resumeSubtractDuration: '0',
	skipBackLength: 10000,
	maxVideoResolution: 'auto',
	playerZoomMode: 'fit',
	mediaSegmentAutoHide: 'off',
	cinemaModeEpisodesEnabled: false,
	trickPlayEnabled: true,
	assDirectPlay: true,
	audioPassthroughMode: 'auto',
	maxAudioChannels: 0,
	downmixToStereo: false,
	syncPlayAdvancedCorrectionEnabled: true,
	syncPlayEnableSyncCorrection: true,
	syncPlayUseSkipToSync: true,
	syncPlayMinDelaySkipToSync: 2000,
	syncPlayExtraTimeOffset: 0,
	autoPlay: true,
	// Off by default because every intro costs a full player teardown and reopen before
	// the film, which is slow on older sets.
	cinemaModeEnabled: false,
	theme: 'dark',
	visualTheme: 'moonfin',
	customThemeId: '',
	homeRows: DEFAULT_HOME_ROWS,
	pluginSections: [],
	displayFavoritesRows: false,
	displayCollectionsRows: false,
	displayGenresRows: false,
	displayPlaylistsRows: false,
	// Which rows the music library shows, and how they sort.
	displayAudioLatest: true,
	displayAudioLastPlayed: true,
	displayAudioFavorites: true,
	displayAudioPlaylists: true,
	displayAudioAlbumArtists: true,
	displayAudioArtists: true,
	displayAudioAlbums: true,
	audioSortOption: 'name',
	customHomeRows: [],
	recentlyReleasedSeriesType: 'series',
	mergeRadarrSonarrCalendars: false,
	radarrCalendarShowCinema: true,
	radarrCalendarShowDigital: true,
	radarrCalendarShowPhysical: true,
	radarrCalendarShowDate: true,
	sonarrCalendarShowDate: true,
	sonarrCalendarShowEpisodeInfo: true,
	favoritesRowSortBy: 'SortName',
	collectionsRowSortBy: 'PlaylistOrder',
	genresRowSortBy: 'SortName',
	genresRowItemFilter: 'all',
	playlistsRowSortBy: 'PlaylistOrder',
	audioRowsSortBy: 'SortName',
	// Auto keeps the direction each sort field always implied.
	favoritesRowSortOrder: 'auto',
	collectionsRowSortOrder: 'auto',
	genresRowSortOrder: 'auto',
	playlistsRowSortOrder: 'auto',
	audioRowsSortOrder: 'auto',
	displayAudioRows: false,
	displayRewatchRow: true,
	playlistsRowShowEpisodes: false,
	displayStudiosRows: false,
	studiosRowSortBy: 'SortName',
	studiosRowSortOrder: 'auto',
	collectionsRowShowEpisodes: false,
	fullScreenRows: false,
	showShuffleButton: true,
	shuffleContentType: 'both',
	showGenresButton: true,
	showFavoritesButton: true,
	showLiveTvButton: true,
	showLibrariesInToolbar: true,
	mergeContinueWatchingNextUp: true,
	mergeRecentRowsByType: false,
	playlistsGroupByType: true,
	nextUpMaxDays: 365,
	hiddenContinueWatchingItems: null,
	hiddenNextUpSeries: null,
	showHomeBackdrop: true,
	backdropBlurHome: 20,
	backdropBlurDetail: 20,
	serverLogging: false,
	diagnosticLoggingEnabled: false,
	featuredContentType: 'both',
	featuredItemCount: 10,
	featuredBarStyle: 'moonfin',
	featuredTrailerPreview: true,
	featuredTrailerMuted: false,
	mediaBarTrailerCaptions: false,
	mediaBarOverlayColor: 'gray',
	mediaBarOverlayOpacity: 50,
	mediaBarSourceType: 'library',
	mediaBarLibraryIds: [],
	mediaBarCollectionIds: [],
	unifiedLibraryMode: false,
	useMoonfinPlugin: false,
	mdblistEnabled: true,
	mdblistRatingSources: ['stars', 'imdb', 'tmdb', 'tomatoes', 'metacritic'],
	tmdbEpisodeRatingsEnabled: true,
	imdbTop250MoviesEnabled: false,
	imdbTop250TvShowsEnabled: false,
	imdbMostPopularMoviesEnabled: false,
	imdbMostPopularTvShowsEnabled: false,
	imdbLowestRatedMoviesEnabled: false,
	imdbTopEnglishMoviesEnabled: false,
	sinceYouWatchedSource: 'local',
	sinceYouWatchedSourceItem: 'recentlyWatched',
	sinceYouWatchedSourceType: 'movies',
	sinceYouWatchedIncludeWatched: false,
	// Pulled from the server plugin, never pushed back. Empty until synced.
	tmdbApiKey: '',
	rewatchIncludeMovies: true,
	rewatchIncludeShows: true,
	rewatchIncludeCollections: true,
	rewatchSortBy: 'recentlyWatched',
	showClock: true,
	clockDisplay: '24-hour',
	// Hours added to every displayed time. Local only, because it corrects this TV
	// rather than the account.
	timeOffsetHours: 0,
	autoLoginBehavior: 'lastUser',
	// The account the currentUser behavior pins, captured when it is chosen.
	autoLoginServerId: '',
	autoLoginUserId: '',
	alwaysAuthenticate: false,
	pinCodeProtection: false,
	pinCode: '0000',
	serverSortBy: 'name',
	exitConfirmation: true,
	updateNotificationsEnabled: true,
	navbarPosition: 'top',
	navbarAlwaysExpanded: false,
	oledMode: 'off',
	screensaverEnabled: true,
	screensaverTimeout: 90,
	screensaverDimmingLevel: 50,
	screensaverClockMode: 'staticCorner',
	screensaverMode: 'library',
	screensaverBackdrop: 'library',
	screensaverComponent: 'moonfinLogo',
	screensaverMovement: 'moderate',
	screensaverPosition: 'middle',
	screensaverSize: 'medium',
	screensaverContentType: 'both',
	screensaverLibraryIds: [],
	screensaverCollectionIds: [],
	screensaverExcludedGenres: [],
	watchedIndicatorBehavior: 'always',
	cardFocusZoom: true,
	useDetailedSubHeadings: true,
	showMediaDetailsOnLibraryPage: true,
	hideBackdropsInLibraries: false,
	useSeriesThumbnails: false,
	homeRowsPosterSize: 'default',
	classicHomeRowsPadding: 30,
	modernHomeRowsPadding: 460,
	homeRowsImageType: 'poster',
	// Per row overrides keyed by row id. An absent id uses the global type above.
	homeRowImageTypes: {},
	homeRowsStyle: 'v2',
	modernCardsOnMyMediaRow: true,
	detailScreenStyle: 'v2',
	personalRatingStyle: 'thumbs',
	detailExpandedTabs: true,
	hideDetailsMediaDescription: false,
	detailUseSeriesThumbnails: false,
	hideHomeMediaDescription: false,
	homeRowOverlay: true,
	folderViewMode: 'local',
	excludedGenres: [],
	autoAdvance: true,
	autoAdvanceInterval: 8,
	nextUpBehavior: 'extended',
	nextUpCountdownStyle: 'both',
	nextUpTimeout: 7,
	stillWatchingBehavior: 'medium',
	skipForwardLength: 30000,
	unpauseRewind: 0,
	showDescriptionOnPause: false,
	// Chosen so the overlay looks unchanged for anyone who never opens the setting.
	playbackTimeAboveLeft: 'none',
	playbackTimeAboveCenter: 'none',
	playbackTimeAboveRight: 'endsAt',
	playbackTimeBelowLeft: 'elapsed',
	playbackTimeBelowCenter: 'none',
	playbackTimeBelowRight: 'totalDuration',
	musicPlaybackTimeDisplay: 'totalDuration',
	introAction: 'ask',
	outroAction: 'ask',
	replaceSkipOutroWithNextUp: false,
	seasonalTheme: 'none',
	themeMusicEnabled: false,
	themeMusicVolume: 30,
	themeMusicOnHomeRows: false,
	themeMusicLoop: true,
	showRatingLabels: true,
	showRatingBadges: true,
	screensaverAgeFilter: false,
	screensaverMaxRating: 13,
	uiScale: 1.0,
	enablePgsRendering: true,
	syncplayEnabled: true,
	syncplayAutoOpen: false,
	showSyncPlayButton: true,
	videoStartDelay: 0,
	liveTvSkipGuide: false,
	stereoUpmixEnabled: false,
	ac3Passthrough: true,
	eac3Passthrough: true,
	dtsPassthrough: true,
	dtshdPassthrough: true,
	truehdPassthrough: true,
	forceTruehdPassthrough: false,
	blockedRatings: [],
	showSeerrButton: true,
	seerrShowMissingCollectionItems: true,
	showSeerrAvailabilityBadges: true,
	// Off until asked for. An admin who wants it on for everyone can set it in the
	// plugin's default settings.
	showServerMessagesButton: false,
	// Synced but not shown anywhere in this app, so null keeps the TV from stamping a default
	// of its own over what another client set.
	showCastButton: null,
	detailShowTechnicalDetails: null,
	recommendationSystemSource: null,
	recommendationsApplyParentalRatingCap: null,
	performanceMode: 'auto',
	// Which keyboard a text field opens. The synced profile keeps one value for every
	// client, and a phone wants the opposite answer a TV does, so this stays local
	// instead of letting a handset decide how the TV types.
	preferSystemImeKeyboard: false,
	focusBorderColor: '',
	navbarOpacity: 50,
	navbarColor: 'gray',
	// webOS TLS proxy fallback: when the WebView rejects a server's certificate
	// (net::ERR_INSECURE_RESPONSE), allow the bundled Node service to fetch with
	// certificate validation disabled. Off by default; local-only (not synced).
	allowInsecureCerts: false
};
